trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: First_job
    steps:
    - bash: echo Build First job
#    - bash: java --version
    - bash: python --version
    - bash: node --version
    - bash: mvn --version            
    - bash: ls -lrth $(System.DefaultWorkingDirectory)
    - bash: ls -lrth 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -lrth $(System.DefaultWorkingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Myartifact'
        publishLocation: 'Container'









    # - bash: echo $(pipeline_level_variable)
  # - job: Second_job
  #   steps:
  #   - bash: echo Build Second job   

# - stage: Devdeploy
#   variables:
#     environment: Dev
#   dependsOn: build
#   jobs:
#   - job: Dev_Deploy_job
#     steps:
#     - bash: echo $(environment) deploy Second job   
# - stage: Prod_Deploy
#   variables:
#     environment: prod
#   dependsOn: build
#   jobs:
#   - job: Prod_Deploy_job
#     steps:
#     - bash: echo $(environment) deploy Second job   
