trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: First_job
    steps:
    - bash: echo Build First job
  - job: Second_job
    steps:
    - bash: echo Build Second job   

- stage: Devdeploy
  jobs:
  - job: Dev_Deploy_job
    steps:
    - bash: echo Dev deploy Second job   
- stage: Prod_Deploy
  jobs:
  - job: Prod_Deploy_job
    steps:
    - bash: echo Prod deploy Second job   
