trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: buildjob
    steps:
    - bash: echo "doing build"
- stage: DevDeploy
  jobs:
  # - job: buildjob
  #   stage:;
  #   - bash: echo "Start deve deploy"
  - deployment: DevDeployjob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev

# steps:
# - script: echo running on $(operatingSystem)
#   displayName: 'Run a one-line script'